### ISSUE TITLE
Adding jerk and snap for generated trajectory

### ISSUE THREAD

**Issue by juanmed** [hbd730/quadcopter-simulation#2]
Hi! 

Its me again. I have not yet started with the previous changes but, was wondering if you could help me with something. I am working on a differential flatness based controller. I need to compute a 4 times differentiable trajectory. I saw in your generate_trajectory method, you compute the velocity and acceleration for the desired trajectory as the first and second derivative of position, which is itself an 
 7 order polynomial. Since I also need jerk and snap, I tried adding the following code in the appropriate sections:

`DesiredState = namedtuple('DesiredState', 'pos vel acc jerk snap yaw yawdot yawddot')`

`yawddot = 0.0`

`    t3 = get_poly_cc(8, 3, scale)
    # apply chain rule
    jerk = np.array([coeff_x[start:end].dot(t3), coeff_y[start:end].dot(t3), coeff_z[start:end].dot(t3)]) * (1.0 / T[t_index]**3)

    t4 = get_poly_cc(8, 4, scale)
    # apply chain rule
    snap = np.array([coeff_x[start:end].dot(t4), coeff_y[start:end].dot(t4), coeff_z[start:end].dot(t4)]) * (1.0 / T[t_index]**4)
`

` return DesiredState(pos, vel, acc, jerk, snap, yaw, yawdot, yawddot)`

Is this the correct way to get the 3th and 4th derivatives of position? I am specially not sure about the division vy "T[t_index]**3" or **4. I just added them to continue with the pattern I saw. 

When I tried running the controller the drone takes an strange path. I will update my branch, but if you could help me with this in the meantime I will appreciate it. Thanks!

Edit: Sorry for the ugly code formatting here. I does not seem to parse properly.

**Comment by hbd730** [comment]
Yes looks like it is the correct place, did drone take strange path without
your change still?

**Comment by juanmed** [comment]
Thanks for the input and sorry for my delayed update. In order to close this issues:

- Snap and jerk trajectory calculation had no influence on the strange path.
- I am not sure, but I think the strange path when using the PID controller is due to a) an error in heading calculation I fixed in[ this commit](https://github.com/juanmed/quadcopter-simulation/commit/f9ca0846282e718a266efe304080d46364ea3401)  or b) high speed trajectories (v>=3)
