### ISSUE TITLE
Euler angle convention used

### ISSUE THREAD

**Issue by juanmed** [hbd730/quadcopter-simulation#4]
Hi! Looking at the code I am almost certain the euler angle convention you used is ZXY. In strict terms and in order of rotations:

1) First, rotation of psi radians around Z axis
2) Then, rotation of phi radians around X axis
3) Finally, rotation of theta radians around Y axis

Could you please confirm if both the euler angle convention and the angles names are like that?

Right now I am implementing a controller based on differential flatness property but my drone always flies in the opposite direction to the generated waypoints, as if the generated trajectory was rotated 180 degress. Thanks.

**Comment by hbd730** [comment]
Hi, thanks for pointing out, yes that sounds right, I also Delft confusing
when programming it, I will confirm and make comments on this.

**Comment by juanmed** [comment]
Hi,

I want to ask if you were able to confirm this?  Also, regarding the world and body frames defined in your simulator, are the axes of both of them aligned? (x,y,z) in world frame aligned with (x,y,z) in body frame? Or did you used some different convention, like north-east-down for world frame and smt different for body frame? 
Thanks for your answer.

**Comment by juanmed** [comment]
I just wanted to confirm that the euler angle convention used is ZXY and that both world and body fixed frames are North-West-Up (or simply the common right-hanede XYZ basis).
