### ISSUE TITLE
Time scaling

### ISSUE THREAD

**Issue by juanmed** [hbd730/quadcopter-simulation#5]
Hi!

I wanted to ask about time scaling done in your simulator. In the generate_trajectory method in trajGen3.py file you calculate T, the "segment travel time", using the sent velocity. If my understanding is right, you divide the "desired state" for each time step by the T corresponding to the segment that "desired state" corresponds.

I wanted to ask about what is the principle for "scaling time" (why dividing by T scales time) and the reasons behind doing this time scaling. It seems to me that this is an artificial way to speed up the simulator, and the drone will not actually fly with the linear velocity sent in the "v" parameter. 

I mean, if I was going to use your desired state and trajectory generator in a real drone, there is no "time scaling", and in the case of a differential flatness based controller, the "desired linear velocities" would be those given by the 2nd derivative of the position, and not related at all with the time scaling applied.

Please correct me if I am wrong. Thanks!

Juan

**Comment by hbd730** [comment]
Hi Juan,

T is not an artificial way to "speed up" the simulation, it depends on the
desired 3D velocity as an input. You can think of time segmented trajectory
as snapshots of the desired pose. Let's say if you want to your drone to
travel from segment A to B within 10ms(calculated by speed that you
specified, assuming it is constant velocity), then it is controller's job
to do whatever it has to do to full fill this requirement - However, this
is then subject to physics constraint, you can't travel at the sped of
light of course, also subject to control loop frequency, if your control
loop is run at 10Hz, which is 100ms, there is no way you can fullfill 10ms
travel request. My understanding is  the T - scaling factor here should
probably be >= control period.

You can basically follow this paper if you want to understand the detail
about MST generation, "minimum snap trajectory"
http://www-personal.acfr.usyd.edu.au/spns/cdm/papers/Mellinger.pdf

For your differential flatness based controller, I am not familiar, but no
matter what controller you are using the interface should stay the same,
from higher level, any planner will just give you a series of time stamped
waypoints, it is your controller's job to spit out the control command as
output to the drone.

Hope this help, btw I added you as contributor, you should just directly
push commits to your branch.

Regards
Peter

**Comment by juanmed** [comment]
Hi, thanks for your answer. I will look at the trajectory section of the paper you mentioned to understand this in detail. 

And thanks for adding me as contributor, I will push my commits there :)
